<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="card">
            <div class="view overlay hm-white-slight">
                <table class="table table-striped table-hover">
                    <thead class="teal lighten-3 ">
                        <tr>
                            <th>Time</th>
                            <th>Theme</th>
                            <th>Author</th>
                            <th>Place</th>
                            <th>Capacity</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="table-active">
                            <td>08:00 - 09:30</td>
                            <td>MES - definition</td>
                            <td>Fidelis Trueman</td>
                            <td>Aula</td>
                            <td>350</td>
                        </tr>
                        <tr>
                            <td>09:40 - 11:00</td>
                            <td>Reading and vision devices</td>
                            <td>Johnny Seen-it-all</td>
                            <td>Meeting room #5</td>
                            <td>80</td>
                        </tr>
                        <tr>
                            <td>10:00 - 11:30</td>
                            <td>Security in low-level systems (PLC's)</td>
                            <td>Shield Blockman</td>
                            <td>Meeting room #2</td>
                            <td>150</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>        