<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <img src="img/mine/whatIsMES.png" class="img-fluid" alt="">
                        <a href="#">
                            <div class="mask"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">What the <strong>MES</strong> is it?</h4>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-teal">Button</a>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <img src="img/mine/whatIsMES.png" class="img-fluid" alt="">
                        <a href="#">
                            <div class="mask"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">What the <strong>MES</strong> is it?</h4>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-teal">Button</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        