<h1>Contact form</h1>
<p>Contact us by sending this form.</p>

<form method="post" id="form-email">
    Your e-mail address<br/>
    <input type="email" name="email" required="required" value="<?php if(isset($_POST['email'])) echo(htmlspecialchars($_POST['email'])); ?>" /><br />
    AntiSPAM - insert actuall year<br />
    <input type="text" name="year" required="required" /><br />
    <textarea name="zprava"><?php if (isset($_POST['zprava'])) echo(htmlspecialchars($_POST['zprava'])); ?></textarea><br />
    <input type="submit" value="Send" />
</form>