<!--Main layout-->
<main class="mt-5">
    <div class="container">

        <div class="row">

            <div class="col-md-5 mb-4">
                <div class="overlay  z-depth-1-half">
                    <img src="img/mine/industry40.jpg" class="img-fluid">
                    <div class="mask"></div>
                </div>
            </div>

            <div class="col-md-7 mb-4">
                <h2>Welcome to MES Conference</h2>
                <hr>
                <p><strong>Manufacturing Execution Systems</strong> are strongly developing and establishing its position in industrial production...</p>
                <p>This website serves as on-line MES conference where registered users can add articles about MES, reviewers can rate them and criticize them and administrators are the gods hands for work that no one else wants to do.</p>
            </div>
        </div>

        <?php echo $articles ?>
        
    </div>
</main>        