<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <h5>Username</h5>   <p><?php echo($user["username"]); ?></p>
                        <h5>E-mail</h5>     <p><?php echo($user["mail"]); ?> </p>
                        <h5>Status</h5>     <p><?php echo($user["status"]);?> </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($articles); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
                            <h3 class="card-title"><?php echo($addTitle); ?></h3>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="title" name="title" placeholder="Title of article" value="<?php echo($editArticle['title']); ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Description</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" rows="4" name="description"><?php echo($editArticle['description']); ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Keywords</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" rows="1" name="keywords"><?php echo($editArticle['keywords']); ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Articles PDF</label>
                                <div class="col-sm-10">
                                    <input type="file" name="fileToUpload" id="fileToUpload">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <?php echo($addButton); ?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        