<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 .mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User info</h4>
                        <p class="card-text"><strong>Name: </strong><?php echo(htmlspecialchars($user["username"])); ?></p>
                        <p class="card-text"><strong>E-mail: </strong><?php echo(htmlspecialchars($user["mail"])); ?> </p>
                        <p class="card-text"><strong>Status: </strong><?php echo(htmlspecialchars($user["status"]));?> </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($reviewsAccepted); ?>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($reviewsNew); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="card-body">
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
                            <h3 class="card-title"><?php echo(htmlspecialchars($addTitle)); ?></h3>
                            <div class="form-group">
                                <label>Overview rating</label>
                                <select class="mdb-select colorful-select dropdown-primary"  name="overview">
                                    <option value="" disabled selected>Overview rating</option>
                                    <option value="1" <?php if($editReview['overview'] == '1'): ?> selected="selected"<?php endif; ?>>1</option>
                                    <option value="2" <?php if($editReview['overview'] == '2'): ?> selected="selected"<?php endif; ?>>2</option>
                                    <option value="3" <?php if($editReview['overview'] == '3'): ?> selected="selected"<?php endif; ?>>3</option>
                                    <option value="4" <?php if($editReview['overview'] == '4'): ?> selected="selected"<?php endif; ?>>4</option>
                                    <option value="5" <?php if($editReview['overview'] == '5'): ?> selected="selected"<?php endif; ?>>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Actuality rating</label>
                                <select class="mdb-select colorful-select dropdown-primary" name="actuality">
                                    <option value="" disabled selected>Actuality rating</option>
                                    <option value="1" <?php if($editReview['actuality'] == '1'): ?> selected="selected"<?php endif; ?>>1</option>
                                    <option value="2" <?php if($editReview['actuality'] == '2'): ?> selected="selected"<?php endif; ?>>2</option>
                                    <option value="3" <?php if($editReview['actuality'] == '3'): ?> selected="selected"<?php endif; ?>>3</option>
                                    <option value="4" <?php if($editReview['actuality'] == '4'): ?> selected="selected"<?php endif; ?>>4</option>
                                    <option value="5" <?php if($editReview['actuality'] == '5'): ?> selected="selected"<?php endif; ?>>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Facts rating</label>
                                <select class="mdb-select colorful-select dropdown-primary" name="facts">
                                    <option value="" disabled selected>Facts rating</option>
                                    <option value="1" <?php if($editReview['facts'] == '1'): ?> selected="selected"<?php endif; ?>>1</option>
                                    <option value="2" <?php if($editReview['facts'] == '2'): ?> selected="selected"<?php endif; ?>>2</option>
                                    <option value="3" <?php if($editReview['facts'] == '3'): ?> selected="selected"<?php endif; ?>>3</option>
                                    <option value="4" <?php if($editReview['facts'] == '4'): ?> selected="selected"<?php endif; ?>>4</option>
                                    <option value="5" <?php if($editReview['facts'] == '5'): ?> selected="selected"<?php endif; ?>>5</option>
                                </select>
                            </div>

                            <div class="form-group basic-textarea">
                                <label class="control-label">Comment</label>
                                <div class="">
                                    <textarea rows="8" name="comment"><?php echo(htmlspecialchars($editReview['comment'])); ?></textarea>
                                </div>
                            </div>
                            <div class="form-group text-right">
                                <div class="">
                                    <?php echo($addButton); ?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Article</h4>
                        <p class="card-text"><strong>Title: </strong><?php echo(htmlspecialchars($article["title"])); ?></p>
                        <p class="card-text"><strong>Author: </strong><?php echo(htmlspecialchars($article["author"])); ?></p>
                        <p class="card-text"><strong>Status: </strong><?php echo(htmlspecialchars($article["status"]));?> </p>
                        <p class="card-text"><strong>Added: </strong><?php echo(htmlspecialchars($article["added"]));?> </p>
                        <p class="card-text"><strong>Modified: </strong><?php echo(htmlspecialchars($article["modified"]));?> </p>
                        <p class="card-text"><strong>Keywords: </strong><?php echo(htmlspecialchars($article["keywords"])); ?> </p>
                        <p class="card-text"><strong>Description: </strong><?php echo(htmlspecialchars($article["description"]));?> </p>
                        <div class="text-center">
                            <?php echo($article["DownloadArticle"]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        