<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <h5 class="card-title">Username</h5>   <p><?php echo($user["username"]); ?></p>
                        <h5 class="card-title">E-mail</h5>     <p><?php echo($user["mail"]); ?> </p>
                        <h5 class="card-title">Status</h5>     <p><?php echo($user["status"]);?> </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($reviewsAccepted); ?>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($reviewsNew); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
                            <h3 class="card-title"><?php echo($addTitle); ?></h3>
                            <div class="form-group">
                                <label>Overview rating</label>
                                <select class="mdb-select colorful-select dropdown-primary"  name="overview">
                                    <option value="" disabled selected>Overview rating</option>
                                    <option value="1" <?php if($editReview['overview'] == '1'): ?> selected="selected"<?php endif; ?>>1</option>
                                    <option value="2" <?php if($editReview['overview'] == '2'): ?> selected="selected"<?php endif; ?>>2</option>
                                    <option value="3" <?php if($editReview['overview'] == '3'): ?> selected="selected"<?php endif; ?>>3</option>
                                    <option value="4" <?php if($editReview['overview'] == '4'): ?> selected="selected"<?php endif; ?>>4</option>
                                    <option value="5" <?php if($editReview['overview'] == '5'): ?> selected="selected"<?php endif; ?>>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Actuality rating</label>
                                <select class="mdb-select colorful-select dropdown-primary" name="actuality">
                                    <option value="" disabled selected>Actuality rating</option>
                                    <option value="1" <?php if($editReview['actuality'] == '1'): ?> selected="selected"<?php endif; ?>>1</option>
                                    <option value="2" <?php if($editReview['actuality'] == '2'): ?> selected="selected"<?php endif; ?>>2</option>
                                    <option value="3" <?php if($editReview['actuality'] == '3'): ?> selected="selected"<?php endif; ?>>3</option>
                                    <option value="4" <?php if($editReview['actuality'] == '4'): ?> selected="selected"<?php endif; ?>>4</option>
                                    <option value="5" <?php if($editReview['actuality'] == '5'): ?> selected="selected"<?php endif; ?>>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Facts rating</label>
                                <select class="mdb-select colorful-select dropdown-primary" name="facts">
                                    <option value="" disabled selected>Facts rating</option>
                                    <option value="1" <?php if($editReview['facts'] == '1'): ?> selected="selected"<?php endif; ?>>1</option>
                                    <option value="2" <?php if($editReview['facts'] == '2'): ?> selected="selected"<?php endif; ?>>2</option>
                                    <option value="3" <?php if($editReview['facts'] == '3'): ?> selected="selected"<?php endif; ?>>3</option>
                                    <option value="4" <?php if($editReview['facts'] == '4'): ?> selected="selected"<?php endif; ?>>4</option>
                                    <option value="5" <?php if($editReview['facts'] == '5'): ?> selected="selected"<?php endif; ?>>5</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Comment</label>
                                <div class="col-sm-11 col-md-12">
                                    <textarea class="form-control" rows="8" name="comment"><?php echo($editReview['comment']); ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <?php echo($addButton); ?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <h4 class="card-title">Article</h4>
                        <h5 class="card-title">Title</h5>   <p><?php echo($article["title"]); ?></p>
                        <h5 class="card-title">Author</h5>   <p><?php echo($article["author"]); ?></p>
                        <h5 class="card-title">Status</h5>     <p><?php echo($article["status"]);?> </p>
                        <h5 class="card-title">Added</h5>     <p><?php echo($article["added"]);?> </p>
                        <h5 class="card-title">Modified</h5>     <p><?php echo($article["modified"]);?> </p>
                        <h5 class="card-title">Keywords</h5>     <p><?php echo($article["keywords"]); ?> </p>
                        <h5 class="card-title">Description</h5>     <textarea class="form-control" rows="8"><?php echo($article["description"]);?> </textarea>
                        <?php echo($article["DownloadArticle"]); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        