<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <h4 class="card-title">Article</h4>
                        <h5 class="card-title">Title</h5>   <p><?php echo($article["title"]); ?></p>
                        <h5 class="card-title">Author</h5>   <p><?php echo($article["author"]); ?></p>
                        <h5 class="card-title">Status</h5>     <p><?php echo($article["status"]);?> </p>
                        <h5 class="card-title">Added</h5>     <p><?php echo($article["added"]);?> </p>
                        <h5 class="card-title">Modified</h5>     <p><?php echo($article["modified"]);?> </p>
                        <h5 class="card-title">Keywords</h5>     <p><?php echo($article["keywords"]); ?> </p>
                        <h5 class="card-title">Description</h5>     <textarea class="form-control" rows="8" disabled><?php echo($article["description"]);?> </textarea>
                        <?php echo($article["DownloadArticle"]); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($reviews); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        