<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 .mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Article</h4>
                        <p class="card-text"><strong>Title: </strong><?php echo($article["title"]); ?></p>
                        <p class="card-text"><strong>Author: </strong><?php echo($article["author"]); ?></p>
                        <p class="card-text"><strong>Status: </strong><?php echo($article["status"]);?> </p>
                        <p class="card-text"><strong>Added: </strong><?php echo($article["added"]);?> </p>
                        <p class="card-text"><strong>Modified: </strong><?php echo($article["modified"]);?> </p>
                        <p class="card-text"><strong>Keywords: </strong><?php echo($article["keywords"]); ?> </p>
                        <p class="card-text"><strong>Description: </strong><?php echo($article["description"]);?> </p>
                        <div class="text-center">
                            <?php echo($article["DownloadArticle"]); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <?php echo($reviews); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        