<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <h5>Username</h5>   <p><?php echo($user["username"]); ?></p>
                        <h5>E-mail</h5>     <p><?php echo($user["mail"]); ?> </p>
                        <h5>Status</h5>     <p><?php echo($user["status"]);?> </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-12 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <table class="table table-striped table-hover">
                            <thead class="teal lighten-3 ">
                                <tr>
                                    <th>Username</th>
                                    <th>Status</th>
                                    <th>E-mail</th>
                                    <th>Registered</th>
                                    <th>Delete</th>
                                    <th>Promote</th>
                                    <th>Neglect</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php echo($userTableRows); ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <table class="table table-striped table-hover">
                            <thead class="teal lighten-3 ">
                                <tr>
                                    <th>Article</th>
                                    <th>Author</th>
                                    <th>Reviews</th>
                                    <th>Status</th>
                                    <th>Reviewer 1</th>
                                    <th>Reviewer 2</th>
                                    <th>Reviewer 3</th>
                                    <th>Change Status</th>
                                    <th>Update</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php echo($reviewsTableRows); ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        