<!--Main layout-->
<main class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 .mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">User info</h4>
                        <p class="card-text"><strong>Name: </strong><?php echo(htmlspecialchars($user["username"])); ?></p>
                        <p class="card-text"><strong>E-mail: </strong><?php echo(htmlspecialchars($user["mail"])); ?> </p>
                        <p class="card-text"><strong>Status: </strong><?php echo(htmlspecialchars($user["status"]));?> </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <table class="table table-striped table-hover">
                            <thead class="teal lighten-3 ">
                                <tr>
                                    <th>Username</th>
                                    <th>Status</th>
                                    <th>E-mail</th>
                                    <th>Registered</th>
                                    <th>Delete</th>
                                    <th>Ban</th>
                                    <th>Promote</th>
                                    <th>Neglect</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php echo($userTableRows); ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 mt-5 .mb-4">
                <div class="card">
                    <div class="view overlay hm-white-slight">
                        <table class="table table-striped table-hover">
                            <thead class="teal lighten-3 ">
                                <tr>
                                    <th>Article</th>
                                    <th>Author</th>
                                    <th>Status</th>
                                    <th>Reviewer 1</th>
                                    <th>Reviewer 2</th>
                                    <th>Reviewer 3</th>
                                    <th>Change Status</th>
                                    <th>Reviews</th>
                                    <th>Update</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php echo($reviewsTableRows); ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>        